Repository Dongjak-Village-Guards/BackEnd, pull requests merged in 2025-08, with the labels that each got.

#3 Setting/2 models
  buynow/.gitignore
  buynow/accounts/__init__.py
  buynow/accounts/admin.py
  buynow/accounts/apps.py
  buynow/accounts/migrations/0001_initial.py
  buynow/accounts/migrations/0002_user_user_discounted_cost_sum_user_user_image_url_and_more.py
  buynow/accounts/migrations/0003_user_is_dummy.py
  buynow/accounts/migrations/0004_remove_user_user_id_remove_user_user_password_and_more.py
  buynow/accounts/migrations/__init__.py
  buynow/accounts/models.py
  buynow/accounts/serializers.py
  buynow/accounts/tests.py
  buynow/accounts/urls.py
  buynow/accounts/views.py
  buynow/config/authentication.py
  buynow/config/settings.py
  buynow/config/urls.py
  buynow/poetry.lock
  buynow/pyproject.toml
  buynow/records/__init__.py
  buynow/records/admin.py
  buynow/records/apps.py
  buynow/records/management/commands/generate_itemrecord_from_db.py
  buynow/records/migrations/0001_initial.py
  buynow/records/migrations/0002_itemrecord_is_dummy.py
  buynow/records/migrations/__init__.py
  buynow/records/models.py
  buynow/records/tests.py
  buynow/records/views.py
  buynow/reservations/__init__.py
  buynow/reservations/admin.py
  buynow/reservations/apps.py
  buynow/reservations/migrations/0001_initial.py
  buynow/reservations/migrations/0002_reservation_is_dummy_userlike_is_dummy.py
  buynow/reservations/migrations/__init__.py
  buynow/reservations/models.py
  buynow/reservations/tests.py
  buynow/reservations/views.py
  buynow/run_with_tunnel.py
  buynow/stores/__init__.py
  buynow/stores/admin.py
  buynow/stores/apps.py
  buynow/stores/data/dongjak_addresses.py
  buynow/stores/data/dummy_store_templates.py
  buynow/stores/management/commands/clear_all_data.py
  buynow/stores/management/commands/generate_dummy_data.py
  buynow/stores/migrations/0001_initial.py
  buynow/stores/migrations/0002_store_is_dummy_storeitem_is_dummy_storemenu_is_dummy_and_more.py
  buynow/stores/migrations/0003_alter_store_store_category.py
  buynow/stores/migrations/__init__.py
  buynow/stores/models.py
  buynow/stores/tests.py
  buynow/stores/urls.py
  buynow/stores/views.py
Labels: enhancement

#6 fix : 예약 목록 조회에서 현재 시간 이후만 조회 필터 추가
  buynow/reservations/views.py
Labels: enhancement

#8 fix : 현재 시간보다 이후의 것만 예약 가능하게끔 + 찜 삭제/예약 조회 관련 오타 수정
  buynow/reservations/views.py
Labels: enhancement, fixed

#10 fix : 카카오 api key 오타 수정
  buynow/config/kakaoapi.py
Labels: fixed

#11 fix : 주소 검색 안되면 중앙대 좌표 반환
  buynow/accounts/urls.py
  buynow/accounts/views.py
  buynow/config/kakaoapi.py
Labels: fixed

#24 Feature/10 5 yesterday
  .idea/dataSources/4dbffb3b-5874-48d2-b966-64007ef3ba11/storage_v2/_src_/schema/sys.zb4BAA.meta
  buynow/config/settings.py
  buynow/pricing/__init__.py
  buynow/pricing/admin.py
  buynow/pricing/apps.py
  buynow/pricing/management/commands/train_and_update_discounts.py
  buynow/pricing/management/commands/yest_update_then_train.py
  buynow/pricing/migrations/0001_initial.py
  buynow/pricing/migrations/__init__.py
  buynow/pricing/models.py
  buynow/pricing/signals.py
  buynow/pricing/tests.py
  buynow/pricing/utils.py
  buynow/pricing/views.py
  buynow/records/migrations/0003_itemrecord_sold.py
  buynow/records/migrations/0004_itemrecord_is_learned.py
  buynow/records/models.py
  buynow/reservations/views.py
  buynow/stores/data/dongjak_addresses.py
  buynow/stores/data/dummy_store_templates.py
  buynow/stores/management/commands/create_store_items.py
  buynow/stores/management/commands/create_unsold_item_records.py
  buynow/stores/management/commands/generate_dummy_data.py
  buynow/stores/migrations/0004_storemenu_dp_weight.py
  buynow/stores/models.py
  buynow/stores/views.py
Labels: enhancement

#30 Feature/10 7 seperate
  buynow/pricing/management/commands/train_records.py
  buynow/pricing/utils.py
Labels: fixed

#41 Feature/10 8 global param
  buynow/pricing/management/commands/train_records.py
  buynow/pricing/management/commands/update_discounts.py
  buynow/pricing/migrations/0002_globalpricingparam.py
  buynow/pricing/models.py
  buynow/pricing/utils.py
  buynow/stores/management/commands/clear_all_data.py
  buynow/stores/management/commands/create_store_items.py
  buynow/stores/management/commands/generate_dummy_data.py
  buynow/stores/management/commands/generate_item_records.py
  buynow/stores/views.py
Labels: enhancement, fixed

#42 Feature/10 8 global param
  buynow/accounts/views.py
  buynow/config/settings.py
  buynow/reservations/views.py
  buynow/stores/models.py
  buynow/stores/views.py
Labels: enhancement

#47 Feature/10 8 global param
  buynow/reservations/views.py
  buynow/stores/views.py
Labels: enhancement

#49 fix: / 삭제
  buynow/config/settings.py
Labels: enhancement
